name: Regenerate products data

on:
  workflow_dispatch: {}
  push:
    paths:
      - 'seed.csv'
    branches:
      - main

jobs:
  mage:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - name: Run Mage
        uses: magefile/mage-action@v3
        with:
          version: latest
          args: seed
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "products.yaml"
          replacesArtifacts: true
          makeLatest: true
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
