name: Regenerate products data

on:
  push:
    paths:
      - 'seed.csv'
    branches:
      - main

jobs:
  mage:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - name: Run Mage
        uses: magefile/mage-action@v3
        with:
          version: latest
          args: seed
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "products.yaml"
          replacesArtifacts: true
          makeLatest: true
